"""Tests for end-to-end pipeline orchestration — PR8."""

from pathlib import Path

import pytest

from contextlens.schemas import (
    CalendarHook,
    ConversationEntities,
    DocumentEntities,
    FailureFlag,
    ImageOutput,
    ImageType,
    QualitySignals,
    ReceiptEntities,
    WhiteboardEntities,
)

ROOT = Path(__file__).resolve().parent.parent
IMG_DIR = ROOT / "data" / "test_images"

# Ensure test images exist (generated by PR7)
pytestmark = pytest.mark.skipif(
    not (IMG_DIR / "img_001.png").exists(),
    reason="Test images not generated yet; run scripts/generate_test_images.py first",
)


# =====================================================================
# Helpers
# =====================================================================

def _process(image_id: str) -> ImageOutput:
    """Process a single test image through the pipeline."""
    from contextlens.pipeline import process_image
    path = IMG_DIR / f"{image_id}.png"
    return process_image(path, image_id=image_id)


# =====================================================================
# Single image — basic output shape
# =====================================================================

class TestSingleImageOutput:
    def test_returns_image_output(self):
        out = _process("img_001")
        assert isinstance(out, ImageOutput)

    def test_image_id_set(self):
        out = _process("img_001")
        assert out.image_id == "img_001"

    def test_type_is_valid_enum(self):
        out = _process("img_001")
        assert isinstance(out.type, ImageType)
        assert out.type != ImageType.UNKNOWN

    def test_type_confidence_in_range(self):
        out = _process("img_001")
        assert 0.0 <= out.type_confidence <= 1.0

    def test_field_confidence_all_in_range(self):
        out = _process("img_001")
        for k, v in out.field_confidence.items():
            assert 0.0 <= v <= 1.0, f"{k}={v} out of [0,1]"

    def test_summary_non_empty(self):
        out = _process("img_001")
        assert len(out.summary) > 0

    def test_quality_signals_present(self):
        out = _process("img_001")
        assert out.quality_signals is not None
        assert isinstance(out.quality_signals, QualitySignals)

    def test_raw_text_non_empty(self):
        out = _process("img_001")
        assert len(out.raw_text) > 0


# =====================================================================
# Receipt — clean (img_001)
# =====================================================================

class TestReceiptClean:
    def test_type_is_receipt(self):
        out = _process("img_001")
        assert out.type == ImageType.RECEIPT

    def test_entities_are_receipt_type(self):
        out = _process("img_001")
        assert isinstance(out.extracted_entities, ReceiptEntities)

    def test_merchant_extracted(self):
        out = _process("img_001")
        assert out.extracted_entities.merchant is not None
        assert len(out.extracted_entities.merchant) > 0

    def test_total_extracted(self):
        out = _process("img_001")
        assert out.extracted_entities.total is not None
        assert out.extracted_entities.total > 0

    def test_items_extracted(self):
        out = _process("img_001")
        assert isinstance(out.extracted_entities.items, list)
        assert len(out.extracted_entities.items) >= 1, (
            "Clean receipt should extract at least one item"
        )

    def test_no_failure_flags(self):
        out = _process("img_001")
        assert out.failure_flags == []

    def test_no_clarification_needed(self):
        out = _process("img_001")
        assert out.needs_clarification is False

    def test_calendar_hook_none(self):
        out = _process("img_001")
        assert out.calendar_hook is None

    def test_high_confidence_on_clean(self):
        out = _process("img_001")
        # Clean image should have all field confidences >= 0.3
        for k, v in out.field_confidence.items():
            assert v >= 0.3, (
                f"Clean receipt field '{k}' has low confidence {v}"
            )


# =====================================================================
# Conversation — meeting reference (img_006)
# =====================================================================

class TestConversationMeeting:
    def test_type_is_conversation(self):
        out = _process("img_006")
        assert out.type == ImageType.CONVERSATION

    def test_entities_are_conversation_type(self):
        out = _process("img_006")
        assert isinstance(out.extracted_entities, ConversationEntities)

    def test_participants_extracted(self):
        out = _process("img_006")
        assert len(out.extracted_entities.participants) >= 2

    def test_calendar_hook_emitted(self):
        out = _process("img_006")
        assert out.calendar_hook is not None
        assert isinstance(out.calendar_hook, CalendarHook)
        assert out.calendar_hook.mentioned is True

    def test_calendar_hook_has_events(self):
        out = _process("img_006")
        assert len(out.calendar_hook.event_candidates) >= 1

    def test_action_items_extracted(self):
        out = _process("img_006")
        assert len(out.extracted_entities.action_items) >= 1


# =====================================================================
# Document — form (img_008)
# =====================================================================

class TestDocumentForm:
    def test_type_is_document(self):
        out = _process("img_008")
        assert out.type == ImageType.DOCUMENT

    def test_entities_are_document_type(self):
        out = _process("img_008")
        assert isinstance(out.extracted_entities, DocumentEntities)

    def test_structured_fields_extracted(self):
        out = _process("img_008")
        assert len(out.extracted_entities.structured_fields) > 0

    def test_document_kind_detected(self):
        out = _process("img_008")
        assert out.extracted_entities.document_kind is not None


# =====================================================================
# Whiteboard — clean (img_011)
# =====================================================================

class TestWhiteboardClean:
    def test_type_is_whiteboard(self):
        out = _process("img_011")
        assert out.type == ImageType.WHITEBOARD

    def test_entities_are_whiteboard_type(self):
        out = _process("img_011")
        assert isinstance(out.extracted_entities, WhiteboardEntities)

    def test_text_blocks_extracted(self):
        out = _process("img_011")
        assert len(out.extracted_entities.text_blocks) > 0

    def test_structure_inferred(self):
        out = _process("img_011")
        structure = out.extracted_entities.inferred_structure
        # Should find bullets, owners, or project tags
        assert (
            len(structure.bullets) > 0
            or len(structure.owners) > 0
            or len(structure.project_tags) > 0
        )


# =====================================================================
# Adversarial — blurry receipt (img_003)
# =====================================================================

class TestBlurryReceipt:
    def test_blurry_flag_set(self):
        out = _process("img_003")
        assert FailureFlag.BLURRY_IMAGE in out.failure_flags

    def test_quality_signals_show_blurry(self):
        out = _process("img_003")
        assert out.quality_signals.is_blurry is True

    def test_confidence_lower_than_clean(self):
        clean = _process("img_001")
        blurry = _process("img_003")
        # Average confidence should be lower for blurry
        if clean.field_confidence and blurry.field_confidence:
            avg_clean = sum(clean.field_confidence.values()) / len(clean.field_confidence)
            avg_blurry = sum(blurry.field_confidence.values()) / len(blurry.field_confidence)
            assert avg_blurry < avg_clean


# =====================================================================
# Adversarial — rotated receipt (img_002)
# =====================================================================

class TestRotatedReceipt:
    def test_rotation_detected(self):
        out = _process("img_002")
        assert out.quality_signals.is_rotated is True

    def test_rotation_flag_set(self):
        out = _process("img_002")
        assert FailureFlag.ROTATION_UNRESOLVED in out.failure_flags

    def test_still_produces_valid_type(self):
        out = _process("img_002")
        assert isinstance(out.type, ImageType)


# =====================================================================
# Batch processing
# =====================================================================

class TestBatchProcessing:
    def test_batch_returns_correct_count(self):
        from contextlens.pipeline import process_batch
        paths = [IMG_DIR / f"img_{i:03d}.png" for i in [1, 5, 8]]
        outputs = process_batch(paths)
        assert len(outputs) == 3

    def test_batch_all_valid_outputs(self):
        from contextlens.pipeline import process_batch
        paths = [IMG_DIR / f"img_{i:03d}.png" for i in [1, 5, 8]]
        outputs = process_batch(paths)
        for out in outputs:
            assert isinstance(out, ImageOutput)
            assert len(out.summary) > 0
            assert out.quality_signals is not None

    def test_batch_with_explicit_ids(self):
        from contextlens.pipeline import process_batch
        paths = [IMG_DIR / "img_001.png", IMG_DIR / "img_005.png"]
        ids = ["test_a", "test_b"]
        outputs = process_batch(paths, image_ids=ids)
        assert outputs[0].image_id == "test_a"
        assert outputs[1].image_id == "test_b"

    def test_batch_mismatched_lengths_raises(self):
        from contextlens.pipeline import process_batch
        with pytest.raises(ValueError):
            process_batch(
                [IMG_DIR / "img_001.png"],
                image_ids=["a", "b"],
            )


# =====================================================================
# Default image_id from filename
# =====================================================================

class TestDefaultImageId:
    def test_image_id_from_stem(self):
        from contextlens.pipeline import process_image
        out = process_image(IMG_DIR / "img_001.png")
        assert out.image_id == "img_001"


# =====================================================================
# Summary generation
# =====================================================================

class TestSummaryGeneration:
    def test_receipt_summary_contains_merchant(self):
        out = _process("img_001")
        if out.type == ImageType.RECEIPT and out.extracted_entities.merchant:
            assert out.extracted_entities.merchant.lower() in out.summary.lower()

    def test_conversation_summary_mentions_participants(self):
        out = _process("img_006")
        if out.type == ImageType.CONVERSATION:
            assert "conversation" in out.summary.lower()

    def test_document_summary_mentions_kind(self):
        out = _process("img_008")
        if out.type == ImageType.DOCUMENT:
            assert "field" in out.summary.lower()

    def test_whiteboard_summary_mentions_tasks(self):
        out = _process("img_011")
        if out.type == ImageType.WHITEBOARD:
            assert "task" in out.summary.lower() or "whiteboard" in out.summary.lower()


# =====================================================================
# Output serialization
# =====================================================================

class TestOutputSerialization:
    def test_output_to_json(self):
        out = _process("img_001")
        json_str = out.model_dump_json()
        assert len(json_str) > 0

    def test_output_to_dict(self):
        out = _process("img_001")
        d = out.model_dump()
        assert isinstance(d, dict)
        assert "image_id" in d
        assert "type" in d
        assert "field_confidence" in d
        assert "summary" in d

    def test_roundtrip(self):
        out = _process("img_001")
        d = out.model_dump()
        restored = ImageOutput(**d)
        assert restored.image_id == out.image_id
        assert restored.type == out.type
